### ISSUE TITLE
Miniaturepets NPC laying eggs issue.

### ISSUE THREAD

**Issue by LavivaNW** [miniaturepets/citizens-integration#1]
- Pets lay eggs when chicken is set as invisible animal.
![image](https://user-images.githubusercontent.com/51966310/96865255-677cee00-1472-11eb-9c4b-1594eea876a3.png)
![image](https://user-images.githubusercontent.com/51966310/96865292-72378300-1472-11eb-9fc6-55d9120ba386.png)

**Comment by incredimike** [comment]
I am also experiencing this issue.

**Comment by liorsl** [comment]
Hello,
Thanks for reporting this bug! It will be solved with MiniaturePets v2.5.4 since this is not a bug in the npcs plugin.
