### ISSUE TITLE
[Feature Request] Title Adjustment

### ISSUE THREAD

**Issue by Elioz** [miniaturepets/citizens-integration#10]
Hi!

Will be nice if in the next update you will add an option to adjust the title above the pet, since they are different,
the text is "inside" the pet or allocate too much left/right,

Thanks in advance :D

**Comment by liorsl** [comment]
Hi Elioz!
It's actually possible right now (Just like it is with normal pets).
You can specify a `nameplateStand` in the pet yml, otherwise it will default to the head. 

Did that help?

**Comment by Elioz** [comment]
> Hi Elioz!
> It's actually possible right now (Just like it is with normal pets).
> You can specify a `nameplateStand` in the pet yml, otherwise it will default to the head.
> 
> Did that help?

Hi Lior,

How it can be done? I mean, what comes after nameplateStand?
