### ISSUE TITLE
[Bug Report] Pet is a baby type. But when I spawn it with the citizens command it spawn a fully grown one

### ISSUE THREAD

**Issue by Tom18314** [miniaturepets/citizens-integration#12]
# Bug Report

### Technical Information
* Server Software: PaperSpigot 1.16.5
* Plugin Version: 2.5.7
* Dump File: https://pastebin.com/raw/Fr2Agcdc
> Use `/mpet dump` to get the dump file.

### General Information

**Bug Description**
Please be as descriptive as possible when describing the bug you are facing, and save no words. Please use a reasonably understandable English, feel free to use stuff like Grammarly to do it.

**Instructions To Produce**
Again, don't save any words, use the format below to describe every step of producing the bug, if you are unsure, try to say what you think caused it.
1. Title says enough
2. 
3. 
4. 

**Logs**
If you have any logs, this is the time to include them, you can use tools like Pastebin or Hastebin to post the links to them here. Alternatively, you can use [Markdown](https://guides.github.com/features/mastering-markdown/).

**Visual Demonstration**
![image](https://user-images.githubusercontent.com/72739475/116885302-06f01a00-ac28-11eb-93ba-9a4cb472e4a9.png)

**Comment by liorsl** [comment]
Hello!
Thanks for the report, it will be fixed in the next version and will include support for the new anchor metadata system.
