### ISSUE TITLE
Problem with "/npc path" command

### ISSUE THREAD

**Issue by LavivaNW** [miniaturepets/citizens-integration#2]
When we use the command used to make npc walk in certain areas in miniaturepets npcs, all npc's are gathered together and broken.

![NPCPath](https://user-images.githubusercontent.com/51966310/96865587-d5291a00-1472-11eb-8095-f8a0eb25fd2e.gif)

**Comment by liorsl** [comment]
Hello there,
This bug will be solved with the next release.
