### ISSUE TITLE
Problem with "/npc tphere" command

### ISSUE THREAD

**Issue by LavivaNW** [miniaturepets/citizens-integration#3]
that when we select 1 npc and call it with the "/ mpet tphere" command, all other npc's come to us.

![image](https://user-images.githubusercontent.com/51966310/96865814-1d483c80-1473-11eb-9e5e-c87cc31bc8a4.png)
![image](https://user-images.githubusercontent.com/51966310/96865831-220cf080-1473-11eb-8e88-e31397640361.png)

**Comment by liorsl** [comment]
Hello,
Thanks for the report! this issue will be resolved in the next release.

**Comment by LavivaNW** [comment]
thx :+1:
