### ISSUE TITLE
There are degradation in npc placed by looking in different directions.

### ISSUE THREAD

**Issue by LavivaNW** [miniaturepets/citizens-integration#4]
Corruption occurs in npc's placed by looking in different directions.
and occurs in npc's placed by looking at different diagonal directions.

![image](https://user-images.githubusercontent.com/51966310/96866571-2c7bba00-1474-11eb-8104-72dee775805a.png)
As seen in 1 and 2, feet and arms are separated from the body when the npc is placed in the east direction.

**Comment by liorsl** [comment]
Hello,
Unfortunately I was not able to reproduce this issue. Which model it is that you are currently using?

**Comment by incredimike** [comment]
I can recreate this issue using a pet created by @LavivaNW . Specifically the Christmas tree pet.

**Comment by ghost** [comment]
@LavivaNW Please open a ticket referencing this issue and sending over the specific pet you are using in this example within 48 hours to reopen this issue.

**Comment by incredimike** [comment]
@danielnaaman I have a pet that causes the issue. Can I send you a download link via DM on discord or something less public?

**Comment by ghost** [comment]
> @danielnaaman I have a pet that causes the issue. Can I send you a download link via DM on discord or something less public?

Unless it's publicly available for free / your pet, you can't.

**Comment by incredimike** [comment]
@danielnaaman I understand the implications. I have permission from the author, @LavivaNW, for this purpose.
