### ISSUE TITLE
Pet NPC will incorrectly teleport when using the /npc move command after /npc select a different NPC

### ISSUE THREAD

**Issue by incredimike** [miniaturepets/citizens-integration#5]
# Bug Report

### Technical Information
* Server Software: Paper latest
* Plugin Version:  latest

### General Information

**Bug Description**
A Pet NPC will incorrectly teleport when using the /npc move command after /npc select a different NPC.

**Instructions To Produce**
1. create a new pet npc `/mpet npc PET_NPC somepet`
2. find a different or create a new vanilla NPC (e.g. `/npc create REGULAR_NPC `) and then run `/npc select` to select the new NPC "REGULAR_NPC"
3. Move yourself to a different location on the map.
4. Run `/npc move` to move REGULAR_NPC to your new location.

Expectation: 
REGULAR_NPC will teleport to player location, and PET_NPC will not be modified at all.

Actual results: Both REGULAR_NPC and PET_NPC are teleported to the Player location.

**Visual Demonstration**
![image](https://user-images.githubusercontent.com/125589/99460053-02d37880-28e4-11eb-8dde-e004d4a64909.png)
In this screenshot, only Frosty was selected but the Xmas Tree was also teleported after running `/npc move`

**Comment by liorsl** [comment]
Hello,
It is duplicated with #3, fix will be released in the next version.
I am gonna close this for now
