### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by codebycam** [miniaturepets/citizens-integration#8]
# Bug Report

### Technical Information
* Server Software: Tuinity 1.16.4
* Plugin Version:  2.5.4
* Dump File: https://pastebin.com/AWR8qAyr

### General Information

**Bug Description**
When spawning pets with `/miniaturepet npc name petName` they spawn incorrectly / not aligned how they should be.
I have noticed with a few pets that they were _okay_ if they were facing a straight direction (North, South, East, West), it seemed to occur more if the pet is facing a diagonal direction. This isn't certain though, an example of the sled below, breaks 100% of the time no matter what way I'm facing when I spawn it.

**Instructions To Produce**
As above.

**Visual Demonstration**
When I summon it as a pet:
![](https://i.imgur.com/UxPpQTx.png)

When I summon it as a NPC:
![](https://i.imgur.com/7zbTcFP.png)

**Comment by liorsl** [comment]
Hello,
I am very sorry for the delayed response. 
The issue was fixed and the patch will be included in the next pair of MiniaturePets and citizens-integration.
